# Generated by Django 4.1.3 on 2023-04-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GesSite', '0002_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='photo_image',
        ),
    ]
